export const short = {
  en_US:
    'Sync backend for the Anytype apps, keeping spaces current across your devices.',
  es_ES:
    'Servidor de sincronización para las apps Anytype, mantiene tus espacios al día.',
  de_DE: 'Sync-Server für die Anytype-Apps, hält deine Spaces überall aktuell.',
  pl_PL:
    'Serwer synchronizacji dla aplikacji Anytype, utrzymuje przestrzenie aktualne.',
  fr_FR:
    'Serveur de synchronisation pour les apps Anytype, garde vos espaces à jour.',
}

export const long = {
  en_US:
    'Runs your own any-sync network so the Anytype desktop and mobile apps sync through your server instead of through Anytype’s. Spaces are end-to-end encrypted either way, so this is not about hiding your notes from anyone — it removes the account, the storage quota, and the dependency on infrastructure you do not control. Your spaces keep syncing whatever happens to the company.\n\nThere is no web interface to log in to. This service generates a network configuration file, which you download from it and load into the Anytype app under Settings → Networks → Self-hosted. Desktop, iOS and Android all support this.\n\nClients reach the server over your local network, a VPN, or a forwarded port. Tor is not an option: the Anytype apps have no proxy support and cannot dial an onion address. A self-hosted network is a separate identity from an anytype.io account, so existing spaces must be exported and re-imported.',
  es_ES:
    'Ejecuta tu propia red any-sync para que las aplicaciones Anytype se sincronicen a través de tu servidor en lugar del de Anytype. Los espacios están cifrados de extremo a extremo en ambos casos, así que no se trata de ocultar tus notas: elimina la cuenta, la cuota de almacenamiento y la dependencia de una infraestructura que no controlas.\n\nNo hay interfaz web. Este servicio genera un archivo de configuración de red que descargas y cargas en la aplicación Anytype en Ajustes → Redes → Autoalojado. Funciona en escritorio, iOS y Android.\n\nLos clientes se conectan por tu red local, una VPN o un puerto redirigido. Tor no es posible: las aplicaciones Anytype no admiten proxy y no pueden conectarse a una dirección onion. Una red autoalojada es una identidad distinta de una cuenta de anytype.io, por lo que los espacios existentes deben exportarse e importarse de nuevo.',
  de_DE:
    'Betreibt dein eigenes any-sync-Netzwerk, damit die Anytype-Apps über deinen Server synchronisieren statt über den von Anytype. Spaces sind in beiden Fällen Ende-zu-Ende-verschlüsselt — es geht also nicht darum, Notizen vor jemandem zu verbergen, sondern darum, Konto, Speicherkontingent und die Abhängigkeit von fremder Infrastruktur loszuwerden. Deine Spaces synchronisieren weiter, was auch immer mit dem Unternehmen geschieht.\n\nEs gibt keine Weboberfläche. Dieser Dienst erzeugt eine Netzwerk-Konfigurationsdatei, die du herunterlädst und in der Anytype-App unter Einstellungen → Netzwerke → Selbst gehostet lädst. Desktop, iOS und Android werden unterstützt.\n\nClients erreichen den Server über dein lokales Netzwerk, ein VPN oder einen weitergeleiteten Port. Tor funktioniert nicht: den Anytype-Apps fehlt jede Proxy-Unterstützung, sie können keine Onion-Adresse aufrufen. Ein selbst gehostetes Netzwerk ist eine eigene Identität, getrennt vom anytype.io-Konto.',
  pl_PL:
    'Uruchamia własną sieć any-sync, dzięki czemu aplikacje Anytype synchronizują się przez Twój serwer zamiast przez serwer Anytype. Przestrzenie są szyfrowane end-to-end w obu przypadkach, więc nie chodzi o ukrywanie notatek — chodzi o usunięcie konta, limitu miejsca i zależności od cudzej infrastruktury. Twoje przestrzenie synchronizują się dalej, niezależnie od losów firmy.\n\nNie ma interfejsu webowego. Usługa generuje plik konfiguracji sieci, który pobierasz i wczytujesz w aplikacji Anytype w Ustawienia → Sieci → Samodzielnie hostowane. Działa na komputerze, iOS i Androidzie.\n\nKlienci łączą się przez sieć lokalną, VPN lub przekierowany port. Tor nie zadziała: aplikacje Anytype nie obsługują proxy i nie połączą się z adresem onion. Sieć samodzielnie hostowana to osobna tożsamość niż konto anytype.io, więc istniejące przestrzenie trzeba wyeksportować i zaimportować ponownie.',
  fr_FR:
    'Exécute votre propre réseau any-sync afin que les applications Anytype se synchronisent via votre serveur plutôt que celui d’Anytype. Les espaces sont chiffrés de bout en bout dans les deux cas : il ne s’agit donc pas de cacher vos notes, mais de supprimer le compte, le quota de stockage et la dépendance à une infrastructure que vous ne contrôlez pas. Vos espaces continuent de se synchroniser quoi qu’il advienne de l’entreprise.\n\nIl n’y a pas d’interface web. Ce service génère un fichier de configuration réseau que vous téléchargez et chargez dans l’application Anytype sous Paramètres → Réseaux → Auto-hébergé. Ordinateur, iOS et Android sont pris en charge.\n\nLes clients joignent le serveur via votre réseau local, un VPN ou un port redirigé. Tor est impossible : les applications Anytype ne gèrent aucun proxy et ne peuvent joindre une adresse onion. Un réseau auto-hébergé est une identité distincte d’un compte anytype.io.',
}
